language: python

cache: pip

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - pypy

matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true

install:
  - pip install -r test-requirements.txt

script:
  pytest --cov=doccron --cov-report=xml -v

after_success:
  codecov

deploy:
  provider: pypi
  user: $TEST_PYPI_USER
  password: $TEST_PYPI_PASS
  server: https://test.pypi.org/legacy/
  distributions: "sdist bdist_wheel"
  on:
    branch: develop
    condition: $TRAVIS_PYTHON_VERSION = "3.6"