environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python37-x64"

install:
  - "%PYTHON%\\Scripts\\pip.exe install -r test-requirements.txt"

build: off

cache:
  - '%LOCALAPPDATA%\pip\Cache'

test_script:
  - "%PYTHON%\\Scripts\\pytest.exe --cov=slugify --cov-report=xml -v"

on_success:
  - "%PYTHON%\\Scripts\\codecov.exe -f coverage.xml"
